apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: streamer-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: streamer-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: streamer-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: streamer-role