apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      run: database
  template:
    metadata:
      labels:
        run: database
    spec:
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-data
      containers:
        - image: postgres:latest
          name: database
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_USER
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-volume
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"