apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: streamer
  namespace: default
  labels:
    run: streamer
spec:
  podSelector:
    matchLabels:
      run: streamer
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 80
  egress: []