apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web
  namespace: default
  labels:
    run: web
spec:
  podSelector:
    matchLabels:
      run: web
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - podSelector:
        matchLabels:
          run: database 
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system  # Allow access to kube-system namespace for DNS
    ports:
    - protocol: UDP
      port: 53  # DNS resolution uses UDP on port 53
