apiVersion: v1
kind: Exception
metadata:
  name: list-secrets-exception
spec:
  justification: "Necessary access to Secrets for operational functionality of MetalLB and Tigera operator."
  resources:
    - kind: Group
      name: kubeadm:cluster-admins
    - kind: ServiceAccount
      name: controller
      namespace: metallb-system
    - kind: ServiceAccount
      name: speaker
      namespace: metallb-system
    - kind: ServiceAccount
      name: tigera-operator
      namespace: tigera-operator
  rules:
    - "C-0015"
